$(document).ready(function(){
    $('#hamburger').click(function(){
     $(this).toggleClass('open');
    });
   });
   $(document).ready(function(){
    $('#hamburger').click(function(){
     $('#menu').toggleClass('open');
    });
   });